[package]
name = "tock-native"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
build = "build.rs"

[profile.dev]
panic = "abort"
lto = true
opt-level = "z"
debug = true

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
debug = true

[dependencies]
tock_native_arch = { path = "../../arch/native" }
tock_native_chip = { path = "../../chips/native" }
capsules = { path = "../../capsules" }
kernel = { path = "../../kernel" }
